### ISSUE TITLE
Configuring tzdata waiting for input

### ISSUE THREAD

**Issue by lucasfsousa** [MGenteluci/cloudformation-deploy-action#3]
Something was changed on github Docker filer that now is asking for input while configuring tzdata:

```
Configuring tzdata
------------------

Please select the geographic area in which you live. Subsequent configuration
questions will narrow this down by presenting a list of cities, representing
the time zones in which they are located.

  1. Africa      4. Australia  7. Atlantic  10. Pacific  13. Etc
  2. America     5. Arctic     8. Europe    11. SystemV
  3. Antarctica  6. Asia       9. Indian    12. US
```

I've fixed this in a fork from the project adding the following code on `Dockerfile`:
```
ENV DEBIAN_FRONTEND=noninteractive
```
https://github.com/r0zar/sam-deploy-action/pull/3

I'll create a PR to fix the problem.

More information about this error can be found it here:
https://askubuntu.com/questions/909277/avoiding-user-interaction-with-tzdata-when-installing-certbot-in-a-docker-contai

**Comment by MGenteluci** [comment]
PR merged! thanks for the contribution!
