### ISSUE TITLE
Stuck in build 

### ISSUE THREAD

**Issue by saymonaraujo** [MGenteluci/cloudformation-deploy-action#6]
Hello, 

I'm trying to use this, and I have used before in another repository and worked fine. But now in the build part keep stuck in this part:

![image](https://user-images.githubusercontent.com/25465421/100935221-9739ff80-34ce-11eb-91b5-c3329e0bdb95.png)

And keeps running. 

Can you solve this ?

Thank you.

**Comment by CarlosMenaPhotoslurp** [comment]
https://askubuntu.com/questions/909277/avoiding-user-interaction-with-tzdata-when-installing-certbot-in-a-docker-contai

**Comment by CarlosMenaPhotoslurp** [comment]
It seems the bug is fixed on master branch. Not released yet: https://github.com/MGenteluci/cloudformation-deploy-action/blob/master/Dockerfile#L14

**Comment by CarlosMenaPhotoslurp** [comment]
https://github.com/MGenteluci/cloudformation-deploy-action/compare/v1.4.0...v1.4.0-beta.0

**Comment by saymonaraujo** [comment]
Understood. 
Thank you Carlos.
